apiVersion: v1
kind: Pod
metadata:
  name: jaeger
  labels:
    app: jaeger-all-in-one
  namespace: monitoring
spec:
  dnsPolicy: ClusterFirst
  containers:
  - name: jaeger
    image: jaegertracing/all-in-one:1.13
    imagePullPolicy: IfNotPresent
    env:
    - name: COLLECTOR_ZIPKIN_HTTP_PORT
      value: "9411"
    ports:
    - containerPort: 16686
      protocol: TCP
    - containerPort: 16687
      protocol: TCP
    - containerPort: 6831
      protocol: UDP
    - containerPort: 6832
      protocol: UDP
    - containerPort: 5778
      protocol: TCP
    - containerPort: 5775
      protocol: UDP
    - containerPort: 14268
      protocol: TCP
    - containerPort: 14269
      protocol: TCP
    - containerPort: 9411
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger
  labels:
    app: jaeger-all-in-one
  namespace: monitoring
spec:
  ports:
  - name: query-tcp-16686
    protocol: TCP
    port: 16686
    targetPort: 16686
  - name: query-tcp-16687
    protocol: TCP
    port: 16687
    targetPort: 16687
  - name: agent-udp-6831
    protocol: UDP
    port: 6831
    targetPort: 6831
  - name: agent-udp-6832
    protocol: UDP
    port: 6832
    targetPort: 6832
  - name: agent-tcp-5778
    protocol: TCP
    port: 5778
    targetPort: 5778
  - name: agent-udp-5775
    protocol: UDP
    port: 5775
    targetPort: 5775
  - name: collector-tcp-14268
    protocol: TCP
    port: 14268
    targetPort: 14268
  - name: collector-tcp-14269
    protocol: TCP
    port: 14269
    targetPort: 14269
  - name: collector-tcp-9411
    protocol: TCP
    port: 9411
    targetPort: 9411
  selector:
    app: jaeger-all-in-one
---
